### ISSUE TITLE
Permission Denied when attempting to build docker

### ISSUE THREAD

**Issue by KMFDManic** [zoltanvb/retroarch-cross-compile#1]
@zoltanvb 

I run a few other compiler setups, and was interested in seeing how your docker build plays out for a few things.  I'd also like to communicate with you about possibly fixing up some of the performance/speed issues with some of your default builds, that would benefit others in the future.  Thanks in advance for your reply:)

I got this error when attempting to build docker:

Edit:
Thanks for the Zlib fix:)

**Comment by zoltanvb** [comment]
Hi, this looks like a common error message when running docker is only allowed for root, so as a first measure, try "sudo docker build ."
Let me know the build issues as well, either here or Discord PM on libretro server would be fine.

**Comment by KMFDManic** [comment]
@zoltanvb thanks for the response.  I sent you a PM on Discord, so we can go over things.  Thanks again:)
