### ISSUE TITLE
Previous core version?

### ISSUE THREAD

**Issue by TheShich** [zoltanvb/retroarch-cross-compile#2]
Thank you for your great work!
Is it possible to get previous core version from your repository somehow?

**Comment by zoltanvb** [comment]
Individual download is possible: check the zip files repository at https://github.com/zoltanvb/zoltanvb.github.io/tree/master/armv7-hf-neon, navigate to the individual core, and to History in the upper right corner. Each update has a "view at this point in history" button, and there you can use "download raw file" option. The repo is updated approx. once per every two weeks, building the last available status at the time, if there was any change.

**Comment by TheShich** [comment]
Thank you so much!
